apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - gotk-components.yaml
  - flux-kustomization.yaml
  - gotk-sync.yaml
  - ../../../namespaces/homelab.yaml
  - ../../../namespaces/cert-manager.yaml
  - ../../../namespaces/monitoring.yaml
