apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tls
  namespace: flux-system
spec:
  path: ./apps/base/certmanager/tls
  prune: true
  wait: true
  interval: 10m
  dependsOn:
    - name: certs-controller
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
